### ISSUE TITLE
项目具体内容

### ISSUE THREAD

**Issue by keiraee** [FantasySilence/DataAnalysisFinal#1]
我想问问，我还没有下载源码，我想知道具体分析的数据是什么

**Comment by FantasySilence** [comment]
你好，58同城二手房

**Comment by FantasySilence** [comment]
> 我想问问，我还没有下载源码，我想知道具体分析的数据是什么

58同城二手房的数据，不建议您下载源码，因为这个项目还未完成，但您可以使用爬取器以及解析器来获取房价数据
